[package]
name = "favia"
version = "0.1.1"
edition = "2021"
description = "Zero-config, content-oriented static site generator"
license = "MIT"

[dependencies]
clap = "4.1.4"
log = "0.4"
simplelog = "^0.12.0"
tera = "1"
anyhow = "1"
markdown = "=1.0.0-alpha.5"
toml = "0.7.1"
serde = "1.0.152"
