[package]
name = "favia"
version = "0.1.0"
edition = "2021"
description = "Zero-config, content-oriented static site generator"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
